main:
#  - name: Home
#    url: '#about'
#    weight: 1
#  - name: About
#    url: /aboutme
#    weight: 2

  - name: Achievements
    url: /pubs/
    weight: 11

  - name: Teaching
    url: /teachings/
    weight: 22
  - name: Outreach
    url: /outreaches/
    weight: 33
  - name: Credits
    url: /creditlists/
    weight: 44
  - name: Projects
    url: /projects/
    weight: 55


#  - name: Posts
#    url: /posts/
#    weight: 66

#  - name: Contact
#    url: /contacts/
#    weight: 66
